import { useEffect, useState } from "react";
import api from "../services/api";

function AlertsPage() {
  const [patients, setPatients] = useState([]);
  const [alerts, setAlerts] = useState([]);

  useEffect(() => {
    const loadAlerts = async () => {
      try {
        const patientsResponse = await api.get("/patients");

        const patientList = patientsResponse.data;

        setPatients(patientList);

        const alertResults = await Promise.all(
          patientList.map(async (patient) => {
            try {
              const response = await api.get(`/patients/${patient.id}/alerts`);

              return response.data.map((alert) => ({
                ...alert,
                patientName: patient.name,
              }));
            } catch {
              return [];
            }
          }),
        );

        setAlerts(alertResults.flat());
      } catch (error) {
        console.error("Failed to load alerts:", error);
      }
    };

    loadAlerts();
  }, []);

  const markAsRead = async (alertId) => {
    try {
      await api.put(`/alerts/${alertId}/read`);

      setAlerts((previous) =>
        previous.map((alert) =>
          alert.id === alertId ? { ...alert, status: "Read" } : alert,
        ),
      );
    } catch (error) {
      console.error(error);
    }
  };

  return (
    <div>
      <div className="dashboard-page-header">
        <div>
          <span className="dashboard-eyebrow">MONITORING</span>

          <h1>Alerts</h1>

          <p>
            Review geo-fence alerts generated by the healthcare monitoring
            system.
          </p>
        </div>
      </div>

      <div className="card">
        {alerts.length === 0 ? (
          <p className="empty-message">No alerts found.</p>
        ) : (
          <div className="table-container">
            <table>
              <thead>
                <tr>
                  <th>Patient</th>
                  <th>Message</th>
                  <th>Status</th>
                  <th>Date</th>
                  <th>Action</th>
                </tr>
              </thead>

              <tbody>
                {alerts.map((alert) => (
                  <tr key={alert.id}>
                    <td>{alert.patientName}</td>

                    <td>{alert.message}</td>

                    <td>
                      {alert.status === "Unread" ? (
                        <span className="status-inactive">Unread</span>
                      ) : (
                        <span className="status-active">Read</span>
                      )}
                    </td>

                    <td>{new Date(alert.created_date).toLocaleString()}</td>

                    <td>
                      {alert.status === "Unread" && (
                        <button
                          className="success-button"
                          onClick={() => markAsRead(alert.id)}
                        >
                          Mark Read
                        </button>
                      )}
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        )}
      </div>
    </div>
  );
}

export default AlertsPage;
